### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#1]
As a User ,
I want to sign up,
So that I can create account 

Acceptance Criteria:
-Should be able to register their account.

**Comment by sahadeb1234** [comment]
![image](https://user-images.githubusercontent.com/63497241/114989961-beaacb00-9eb7-11eb-9ab1-7cf99e39db84.png)

**Comment by Rejina-khanal** [comment]
Sign Up page completed
