### ISSUE TITLE
User Details 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#11]
As a admin,
I want to access user booked form,
So that I can contact users

Acceptance Criteria
-Should be able to store the user details.

**Comment by Anis952** [comment]
![image](https://user-images.githubusercontent.com/62248220/114985592-b1d7a880-9eb2-11eb-8bad-582f20481376.png)

**Comment by sahadeb1234** [comment]
![image](https://user-images.githubusercontent.com/63497241/114986538-d6805000-9eb3-11eb-928d-b5aca8db09cb.png)
