### ISSUE TITLE
Message not displaying after booking tour 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#12]
![image](https://user-images.githubusercontent.com/80932723/118209163-d6aa4600-b487-11eb-86eb-fd06c1db852e.png)

**Step to reproduce:**

1. Go to booking page 
2. Select tour type
3. Enter travelling from
4. Enter travelling to 
5. Select Departing time
6. Select Returning time
7. Enter adult number 
8. Enter children number 
9. Choose travel types 

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by Anis952** [comment]
After finding the bug on this page in the model page there is  an import error then i solved the error so finally bug cleared.
![image](https://user-images.githubusercontent.com/62248220/118228901-b9d33a00-b4aa-11eb-9eae-715361a94f75.png)
