### ISSUE TITLE
Message not displaying for empty field 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#13]
![image](https://user-images.githubusercontent.com/80932723/118210237-edea3300-b489-11eb-9f63-116d0b730057.png)

**Step to reproduce:**
1. Go to signup page 
2. Enter username
3. Enter password 
4. Leave password confirmation empty
5. Click Create Account 

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by Anis952** [comment]
After bug finding the main error there is missing validiation in model.py so, then adding validation the bug is finally cleared
![image](https://user-images.githubusercontent.com/62248220/118229788-54804880-b4ac-11eb-84a3-a7e39b5c135c.png)

**Comment by Rejina-khanal** [comment]
Bug fixed
