### ISSUE TITLE
Design for booking page is not familiar with other page 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#14]
![image](https://user-images.githubusercontent.com/80932723/118211113-538aef00-b48b-11eb-8902-70c6e6310f53.png)

**Step to reproduce:**
Go to booking page

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by sahadeb1234** [comment]
After finding the bug then there is not matched RGB color in CSS and after solving this finally bug is cleared.
![image](https://user-images.githubusercontent.com/63497241/118231250-9611f300-b4ae-11eb-97f5-51b87888312f.png)
