### ISSUE TITLE
Search function is not working 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#15]
![image](https://user-images.githubusercontent.com/80932723/118211557-05c2b680-b48c-11eb-9fd6-b2046511e32a.png)

**Step to reproduce:**

1. Go to the home page
2. Enter place name in search 
3. Not showing any result 

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by Anis952** [comment]
After finding a bug on this page there is an error of missing query and then finally cleared a bug and the output is in below screenshot

![image](https://user-images.githubusercontent.com/62248220/118288402-20c91100-b4f4-11eb-97a6-2ac78b5995c5.png)

**Comment by eshwor14** [comment]
the bug which was found has be fixed
![Screenshot (249)](https://user-images.githubusercontent.com/83009277/118395737-af13d300-b66b-11eb-92b1-f230fd7dd696.png)
