### ISSUE TITLE
Manage navigation bar options in Register Page 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#16]
![image](https://user-images.githubusercontent.com/80932723/118213179-27706d80-b48d-11eb-8066-5e629bd73a2b.png)

**Step to reproduce:**
1. Go to register page

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by sahadeb1234** [comment]
After finding the bug there is error  html and  CSS and after solving this finally bug is cleared
![image](https://user-images.githubusercontent.com/63497241/118231964-9494fa80-b4af-11eb-9e7c-5248f32cb673.png)
