### ISSUE TITLE
No any response on clicking read more 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#17]
![image](https://user-images.githubusercontent.com/80932723/118214251-1e809b80-b48f-11eb-86a2-bcec56d35831.png)

**Step to reproduce:**

1. Go to home page 
2. Scroll down to popular packages 
3. Click Read More
4. Not showing any result

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by Anis952** [comment]
After finding a bug in readmore there is the error in code where id is not matched for all so it does not work after solving this the bug was cleared

![image](https://user-images.githubusercontent.com/62248220/118230612-ab3a5200-b4ad-11eb-89e6-06c15a150946.png)

**Comment by eshwor14** [comment]
the bug has been 
![Screenshot (252)](https://user-images.githubusercontent.com/83009277/118395853-51cc5180-b66c-11eb-8ab3-710c8c83bafc.png)
fixed
