### ISSUE TITLE
Not showing message to user about account created or not 

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#18]
![image](https://user-images.githubusercontent.com/80932723/118354653-caa7ac80-b58b-11eb-812f-3daea6b8dd89.png)

### **Step to reproduce:**

1. Go to signup page
2. Fill all the field 
3. Click Create Account
4. Not showing any message 

**Environment** : Chrome on Windows Version 90.0.4430.212

**Comment by SanjibSah** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/80502267/118355272-d052c180-b58e-11eb-840d-6a2f752c1e15.png)
![Screenshot (272)](https://user-images.githubusercontent.com/80502267/118355275-d183ee80-b58e-11eb-803e-594751101ad3.png)

**Comment by SanjibSah** [comment]
I have added one code in view.py page in customerregistration function. And the code is 
return HttpResponse("Thanks for Register! Now you can login.")
