### ISSUE TITLE
Add Details

### ISSUE THREAD

**Issue by Rejina-khanal** [Anis952/Django#8]
As a admin,
I want to add details,
So that I can include new details. 

Acceptance Criteria
-Should have the option of adding places, details and images.

**Comment by Anis952** [comment]
![image](https://user-images.githubusercontent.com/62248220/114988168-be113500-9eb5-11eb-9008-852e5f9da047.png)

**Comment by sahadeb1234** [comment]
![image](https://user-images.githubusercontent.com/63497241/114988143-b6519080-9eb5-11eb-849f-53e96ff34189.png)
